# Site settings
title: Fred Pan
email: fredpan@usc.edu
description: > # keep this and put description below
  Game programmer and designer
  USC Computer Science Games major
  Have developed several video games independently
  Have worked on a teamwork puzzle-solving board game
url: "https://fluffyfred.github.io" # the base hostname & protocol for your site
linkedin_url: www.linkedin.com/in/fredyizhoupan
github_username: fluffyfred
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
