# Site settings
title: Fred Pan
email: fredpan@usc.edu
description: > # keep this and put description below
  Game Programmer and Designer
url: "https://fluffyfred.github.io" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/fredyizhoupan"
github_username: fluffyfred
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
